### ISSUE TITLE
Failed to read some pngs

### ISSUE THREAD

**Issue by Noitidart** [arian/pngjs#10]
This was failing to read some pngs, it would read it but give me instead of rgba its was like just r array. it was weird. I switched to this one - https://github.com/devongovett/png.js - and it works very well. Maybe you can apply the stuff from there to here? The other advantage of devon govett's png.js is that it doesn't need browserify for those that want to use it in Web Workers like me.

**Comment by arian** [comment]
Can you be more specific? Which pngs?

Now this issue isn't very helpful. Also the browserify thing is something completely different.

**Comment by Noitidart** [comment]
I attached the image that it would fail to read.

![64](https://cloud.githubusercontent.com/assets/6372489/18246667/ff66c0de-7321-11e6-8984-b1220ad6cbfe.png)
